# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
# Put the host machine's IP into the authorised_keys file on the VM
if [ -r /vagrant/id_rsa.pub ]; then
        mkdir -p $HOME/.ssh && cat /vagrant/id_rsa.pub >> $HOME/.ssh/authorized_keys
fi
# Repair "==> default: stdin: is not a tty" message
sudo ex +"%s@DPkg@//DPkg" -cwq /etc/apt/apt.conf.d/70debconf
sudo dpkg-reconfigure debconf -f noninteractive -p critical
# Update OS
sudo apt-get update
sudo apt-get install ansible -y
# Repair "==> default: stdin: is not a tty" message
sudo ex +"%s@DPkg@//DPkg" -cwq /etc/apt/apt.conf.d/70debconf
sudo dpkg-reconfigure debconf -f noninteractive -p critical
sudo apt upgrade -y &>/dev/null
sudo shutdown -r now
SCRIPT

# 2 = version of configuration file for Vagrant 1.1+ leading up to 2.0.x
Vagrant.configure("2") do |config|

  config.vm.define :nagios_server do |nagios_server|
    nagios_server.vm.box = "generic/ubuntu2204"
    nagios_server.vm.synced_folder ".", "/vagrant"
    nagios_server.vm.hostname = "Nagios.Server"
    nagios_server.vm.network :private_network, ip: '192.168.50.55'
    nagios_server.vm.provision "shell", inline: $script, privileged: false
    # nagios_server.vm.provision "shell", inline: $script2, privileged: false
  end


  # config.vm.define :u22_builder_1 do |u22_builder_1|
  #   u22_builder_1.vm.box = "generic/ubuntu2204"
  #   u22_builder_1.vm.synced_folder ".", "/vagrant"
  #   u22_builder_1.vm.hostname = "Nagios.Builder.1"
  #   u22_builder_1.vm.network :private_network, ip: '192.168.50.56'
  #   u22_builder_1.vm.provision "shell", inline: $script, privileged: false
  # end
  #
  # config.vm.define :u22_tester_1 do |u22_tester_1|
  #   u22_tester_1.vm.box = "generic/ubuntu2204"
  #   u22_tester_1.vm.synced_folder ".", "/vagrant"
  #   u22_tester_1.vm.hostname = "Nagios.Tester.1"
  #   u22_tester_1.vm.network :private_network, ip: '192.168.50.57'
  #   u22_tester_1.vm.provision "shell", inline: $script, privileged: false
  # end

  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.memory = 4096
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end
end
