#!/usr/bin/env python3

# Some portions generated by IBM Bob

import sys
import jenkins
from pathlib import Path
from dotenv import load_dotenv
import os

def getIP(nodeConfig):
    find1 = nodeConfig.find("<host>") + 6
    find2 = nodeConfig.find("</host>")
    if find1 > 5 and find2 > -1:
        ip = nodeConfig[find1:find2]
        return ip
    else:
        return None
    
def getNodePort(nodeConfig):
    find1 = nodeConfig.find("<port>") + 6
    find2 = nodeConfig.find("</port>")
    if find1 > 5 and find2 > -1:
        port = nodeConfig[find1:find2]
        return port
    else:
        return None
    
def createServer(username, password, url):
    try:
        server = jenkins.Jenkins(url=url, username=username,
                            password=password)
        return server

    except Exception as e:
        print("Error: Could not connect to Jenkins server")
        return sys.exit(1)

def getNodeList(url, username, password):

    try:
        # Create collectedInfo directory if it doesn't exist
        script_dir = Path(__file__).parent
        collected_info_dir = script_dir / "collectedInfo"
        collected_info_dir.mkdir(exist_ok=True)
        
        # Define machine.list file path
        machine_list_path = collected_info_dir / "machine.list"
        
        # Remove existing file if it exists
        if machine_list_path.exists():
            machine_list_path.unlink()
            
        # Connect to Jenkins
        server = createServer(username, password, url)
        nodes = server.get_nodes()
        
        # Create new machine.list file and write node information
        with open(machine_list_path, 'w') as f:
            for node in nodes:
                if "build" in node["name"] or "test" in node["name"] or "dockerhost" in node["name"]:
                    config = server.get_node_config(node["name"])
                    ip = getIP(config)
                    port = getNodePort(config)
                    f.write(f"{node['name']} {ip} {port}\n")
        
        print(f"Machine list saved to: {machine_list_path}")
        
    except jenkins.JenkinsException as e:
        print(f"Jenkins error: {e}")
        return None
    except Exception as e:
        print(f"Error: {e}")
        return None

if __name__ == "__main__":
    # Load environment variables from .env file
    script_dir = Path(__file__).parent
    env_path = script_dir / ".env"
    load_dotenv(env_path)

    url = os.getenv('url')
    username = os.getenv('username')
    password = os.getenv('password')
    
    if not all([url, username, password]):
        print("Error: Missing credentials in .env file")
        print("Required variables: url, username, password")
        sys.exit(1)
    
    getNodeList(url, username, password)
