#!/usr/bin/env python3

# Some portions generated by IBM Bob

from platform import node
import sys
import subprocess
from pathlib import Path
from getNodeList import getNodeList
from dotenv import load_dotenv
import os

# ANSI color codes
GREEN = '\033[92m'
RED = '\033[91m'
CYAN = '\033[96m'
RESET = '\033[0m'

UNIX_LOG_PATH="/var/log/machine_info.json"
WINDOWS_LOG_PATH="c:\\machine_info.json"

def scp_machine_info(node_name, ip, port, collected_info_dir, log_path):

    if ip is None or ip == "None" or port is None or port == "None":
        print(f"  {CYAN}[SKIP]{RESET} {node_name}: IP or port is None")
        return False
    
    local_filename = f"{node_name}_machine_info.json"
    local_filepath = collected_info_dir / local_filename
    
    # Use nagios user to SCP the file
    remote_location = f"nagios@{ip}:{log_path}"
    scp_command = [
        "scp",
        "-P", port,
        "-o", "StrictHostKeyChecking=no",
        "-o", "ConnectTimeout=5",
        "-o", "NumberOfPasswordPrompts=0",
        remote_location,
        str(local_filepath)
    ]
    
    print(f"  [INFO] Copying from {node_name} ({ip}:{port})...")
    
    try:
        result = subprocess.run(
            scp_command,
            capture_output=True,
            text=True,
            timeout=30
        )
        
        if result.returncode == 0:
            print(f"  {GREEN}[SUCCESS]{RESET} File saved to {local_filename}")
            return True
        else:
            print(f"  {RED}[ERROR]{RESET} SCP failed for {node_name}: {result.stderr.strip()}")
            return False
            
    except subprocess.TimeoutExpired:
        print(f"  {RED}[ERROR]{RESET} SCP timeout for {node_name}")
        return False
    except Exception as e:
        print(f"  {RED}[ERROR]{RESET} Exception for {node_name}: {e}")
        return False


def main():
    
    # Load environment variables from .env file
    script_dir = Path(__file__).parent
    env_path = script_dir / ".env"
    load_dotenv(env_path)
    
    url = os.getenv('url')
    username = os.getenv('username')
    password = os.getenv('password')
    
    if not all([url, username, password]):
        print(f"{RED}[ERROR]{RESET} Missing credentials in .env file")
        print("Required variables: url, username, password")
        return 1

    # Generate machine list from Jenkins
    print("\nFetching node list from Jenkins...")
    getNodeList(url, username, password)
    collected_info_dir = script_dir / "collectedInfo"
    machine_list_path = collected_info_dir / "machine.list"
    
    if not machine_list_path.exists():
        print(f"Error: machine.list not found at {machine_list_path}")
        return 1
    
    # Remove any existing *_machine_info.json files from collectedInfo directory
    print("\nCleaning up old machine_info.json files...")
    for old_file in collected_info_dir.glob("*_machine_info.json"):
        old_file.unlink()
        print(f"  Removed: {old_file.name}")
    
    # Read machine list and collect files
    print("\nCollecting machine_info.json from each machine:")
    successful = 0
    failed = 0
    
    with open(machine_list_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            
            parts = line.split()
            if len(parts) >= 3:
                node_name = parts[0]
                ip = parts[1]
                port = parts[2]

                # Skip orka nodes
                if "orka" in node_name:
                    continue
                # SCP only from non windows machines for now
                if scp_machine_info(node_name, ip, port, collected_info_dir, UNIX_LOG_PATH):
                    successful += 1
                else:
                    failed += 1
    
    # Print summary
    print(f"\n{'='*60}")
    print(f"Collection Summary:")
    print(f"  Successful: {successful}")
    print(f"  Failed: {failed}")
    print(f"{'='*60}")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
