#!/usr/bin/env python3

# Some portions generated by IBM Bob

import os
import sys
import platform
import subprocess
import socket
import json
from datetime import datetime
import shutil
import tempfile

OUTPUT_FILE = "/var/log/machine_info.json"

def get_timestamp():
    return datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

def get_hostname():
    try:
        return socket.gethostname()
    except Exception:
        return "Unable to determine"

def get_architecture():
    try:
        result = subprocess.run(['uname', '-p'],
                              capture_output=True, text=True, timeout=5)
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    try:
        return platform.machine()
    except Exception:
        pass
    
    return "Unknown"

def get_os_info():
    os_name = "AIX"
    os_version = ""
    kernel_version = ""
    
    try:
        result = subprocess.run(['oslevel'],
                              capture_output=True, text=True, timeout=5)
        if result.returncode == 0:
            os_version = result.stdout.strip()
    except Exception:
        pass
    
    try:
        result = subprocess.run(['uname', '-v'],
                              capture_output=True, text=True, timeout=5)
        if result.returncode == 0:
            version = result.stdout.strip()
            result = subprocess.run(['uname', '-r'],
                                  capture_output=True, text=True, timeout=5)
            if result.returncode == 0:
                release = result.stdout.strip()
                kernel_version = f"{version}.{release}"
    except Exception:
        pass
    
    technology_level = ""
    try:
        result = subprocess.run(['oslevel', '-s'],
                              capture_output=True, text=True, timeout=5)
        if result.returncode == 0:
            technology_level = result.stdout.strip()
    except Exception:
        pass
    
    return {
        'name': os_name,
        'version': os_version,
        'kernel': kernel_version,
        'technology_level': technology_level,
        'architecture': get_architecture()
    }

def check_packages():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    packages_file = os.path.join(script_dir, '../packages/aix')
    
    try:
        with open(packages_file, 'r') as f:
            packages_data = json.load(f)
    except Exception as e:
        return {
            'build_packages': {},
            'test_packages': {},
            'error': f'Unable to load packages file: {e}'
        }
    
    results = {
        'build_packages': {},
        'test_packages': {}
    }
    
    for package_info in packages_data.get('build_packages', []):
        package_name = package_info.get('name', package_info) if isinstance(package_info, dict) else package_info
        package_path = package_info.get('path', 'default') if isinstance(package_info, dict) else 'default'
        
        if package_path != 'default' and os.path.isfile(package_path) and os.access(package_path, os.X_OK):
            path = package_path
        else:
            path = shutil.which(package_name)
        
        results['build_packages'][package_name] = {
            'installed': path is not None,
            'path': path
        }
    
    for package_info in packages_data.get('test_packages', []):
        package_name = package_info.get('name', package_info) if isinstance(package_info, dict) else package_info
        package_path = package_info.get('path', 'default') if isinstance(package_info, dict) else 'default'
        
        if package_path != 'default' and os.path.isfile(package_path) and os.access(package_path, os.X_OK):
            path = package_path
        else:
            path = shutil.which(package_name)
        
        results['test_packages'][package_name] = {
            'installed': path is not None,
            'path': path
        }
    
    return results

def collect_info():
    return {
        'timestamp': get_timestamp(),
        'hostname': get_hostname(),
        'os': get_os_info(),
        'packages': check_packages()
    }

def write_output(data):
    try:
        with tempfile.NamedTemporaryFile(mode='w', delete=False, 
                                        prefix='machine_info_', suffix='.tmp') as temp_file:
            temp_path = temp_file.name
            json.dump(data, temp_file, indent=2)
        
        try:
            shutil.move(temp_path, OUTPUT_FILE)
            os.chmod(OUTPUT_FILE, 0o644)
            print(f"Machine information successfully written to: {OUTPUT_FILE}")
            return True
        except PermissionError:
            print(f"Error: Unable to write to {OUTPUT_FILE}")
            print("Please ensure you have appropriate permissions (try running with sudo)")
            print(f"Temporary output saved to: {temp_path}")
            return False
        except Exception as e:
            print(f"Error: Unable to write to {OUTPUT_FILE}: {e}")
            print(f"Temporary output saved to: {temp_path}")
            return False
    
    except Exception as e:
        print(f"Error creating temporary file: {e}")
        return False


def main():
    print("Collecting AIX machine information...")
    
    output_dir = os.path.dirname(OUTPUT_FILE)
    if not os.access(output_dir, os.W_OK):
        print(f"Warning: No write permission to {output_dir}")
        print("You may need to run this script with sudo")
        print("")
    
    data = collect_info()
    
    if write_output(data):
        print("")
        print("You can view the report with:")
        print(f"  cat {OUTPUT_FILE}")
        print(f"  python3 -m json.tool {OUTPUT_FILE}")
        return 0
    else:
        return 1

if __name__ == "__main__":
    sys.exit(main())
