#!/usr/bin/env python3

# Some portions generated by IBM Bob

import os
import sys
import platform
import subprocess
import socket
import json
from datetime import datetime
import shutil
import tempfile
import re

OUTPUT_FILE = "/var/log/machine_info.json"

def get_timestamp():
    return datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

def get_hostname():
    try:
        return socket.gethostname()
    except Exception:
        try:
            with open('/etc/hostname', 'r') as f:
                return f.read().strip()
        except Exception:
            return "Unable to determine"

def get_architecture():
    try:
        return platform.machine()
    except Exception:
        try:
            result = subprocess.run(['uname', '-m'],
                                  capture_output=True, text=True, timeout=5)
            if result.returncode == 0:
                return result.stdout.strip()
        except Exception:
            pass
    return "Unknown"

def get_os_info():
    os_name = ""
    os_version = ""
    kernel_version = ""
    
    try:
        kernel_version = platform.release()
    except Exception:
        pass
    
    try:
        if os.path.exists('/etc/os-release'):
            with open('/etc/os-release', 'r') as f:
                os_release = {}
                for line in f:
                    if '=' in line:
                        key, value = line.strip().split('=', 1)
                        os_release[key] = value.strip('"')
                
                os_name = os_release.get('NAME', 'Linux')
                os_version = os_release.get('VERSION', os_release.get('VERSION_ID', 'Unknown'))
        
        elif os.path.exists('/etc/redhat-release'):
            with open('/etc/redhat-release', 'r') as f:
                content = f.read().strip()
                os_name = ' '.join(content.split()[:2])
                version_match = re.search(r'\d+\.\d+', content)
                if version_match:
                    os_version = version_match.group()
        
        elif os.path.exists('/etc/debian_version'):
            os_name = "Debian"
            with open('/etc/debian_version', 'r') as f:
                os_version = f.read().strip()
        
        elif os.path.exists('/etc/SuSE-release'):
            os_name = "SUSE"
            with open('/etc/SuSE-release', 'r') as f:
                for line in f:
                    if 'VERSION' in line:
                        os_version = line.split('=')[1].strip()
                        break
        
        elif os.path.exists('/etc/alpine-release'):
            os_name = "Alpine Linux"
            with open('/etc/alpine-release', 'r') as f:
                os_version = f.read().strip()
        else:
            os_name = "Linux"
            
    except Exception:
        os_name = "Linux"
    
    return {
        'name': os_name,
        'version': os_version,
        'kernel': kernel_version,
        'architecture': get_architecture()
    }

def check_packages():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    packages_file = os.path.join(script_dir, '../packages/linux')
    
    try:
        with open(packages_file, 'r') as f:
            packages_data = json.load(f)
    except Exception as e:
        return {
            'build_packages': {},
            'test_packages': {},
            'error': f'Unable to load packages file: {e}'
        }
    
    results = {
        'build_packages': {},
        'test_packages': {}
    }
    
    for package in packages_data.get('build_packages', []):
        path = shutil.which(package)
        results['build_packages'][package] = {
            'installed': path is not None,
            'path': path
        }
    
    for package in packages_data.get('test_packages', []):
        path = shutil.which(package)
        results['test_packages'][package] = {
            'installed': path is not None,
            'path': path
        }
    
    return results

def collect_info():
    return {
        'timestamp': get_timestamp(),
        'hostname': get_hostname(),
        'os': get_os_info(),
        'packages': check_packages()
    }

def write_output(data):
    try:
        with tempfile.NamedTemporaryFile(mode='w', delete=False, 
                                        prefix='machine_info_', suffix='.tmp') as temp_file:
            temp_path = temp_file.name
            json.dump(data, temp_file, indent=2)
        
        try:
            shutil.move(temp_path, OUTPUT_FILE)
            os.chmod(OUTPUT_FILE, 0o644)
            print(f"Machine information successfully written to: {OUTPUT_FILE}")
            return True
        except PermissionError:
            print(f"Error: Unable to write to {OUTPUT_FILE}")
            print("Please ensure you have appropriate permissions (try running with sudo)")
            print(f"Temporary output saved to: {temp_path}")
            return False
        except Exception as e:
            print(f"Error: Unable to write to {OUTPUT_FILE}: {e}")
            print(f"Temporary output saved to: {temp_path}")
            return False
    
    except Exception as e:
        print(f"Error creating temporary file: {e}")
        return False

def main():
    print("Collecting machine information...")
    
    output_dir = os.path.dirname(OUTPUT_FILE)
    if not os.access(output_dir, os.W_OK):
        print(f"Warning: No write permission to {output_dir}")
        print("You may need to run this script with sudo")
        print("")
    
    data = collect_info()
    
    if write_output(data):
        print("")
        print("You can view the report with:")
        print(f"  cat {OUTPUT_FILE}")
        print(f"  jq . {OUTPUT_FILE}")
        return 0
    else:
        return 1

if __name__ == "__main__":
    sys.exit(main())
