# Some portions generated by IBM Bob

$OutputFile = "$HOME\machine_info.json"

function Get-Timestamp {
    return (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
}

function Get-HostnameInfo {
    try {
        return $env:COMPUTERNAME
    }
    catch {
        return "Unable to determine"
    }
}

function Get-Architecture {
    try {
        $arch = Get-CimInstance -ClassName Win32_Processor -ErrorAction Stop | Select-Object -First 1
        switch ($arch.Architecture) {
            0 { return "x86" }
            5 { return "arm" }
            9 { return "x64" }
            12 { return "arm64" }
            default { return "unknown" }
        }
    }
    catch {
        try {
            switch (($env:PROCESSOR_ARCHITECTURE | ForEach-Object { $_.ToUpperInvariant() })) {
                "X86" { return "x86" }
                "AMD64" { return "x64" }
                "ARM" { return "arm" }
                "ARM64" { return "arm64" }
                default { return "unknown" }
            }
        }
        catch {
            return "unknown"
        }
    }
}

function Get-OSInfo {
    $osInfo = @{
        name = "Windows"
        version = ""
        build = ""
        architecture = ""
    }
    
    try {
        $os = Get-CimInstance -ClassName Win32_OperatingSystem -ErrorAction Stop
        $osInfo.name = $os.Caption
        $osInfo.version = $os.Version
        $osInfo.build = $os.BuildNumber
        $osInfo.architecture = Get-Architecture
    }
    catch {
        Write-Warning "Unable to retrieve OS information: $_"
    }
    
    return $osInfo
}

function Get-CommandPath {
    param(
        [string]$Command
    )
    
    $path = Get-Command $Command -ErrorAction SilentlyContinue
    if ($path) {
        return $path.Source
    }
    return $null
}

function Test-PackageInstalled {
    param(
        [string]$Package
    )
    
    $path = Get-CommandPath -Command $Package
    return @{
        installed = ($null -ne $path)
        path = $path
    }
}

function Get-PackageInfo {
    $scriptDir = Split-Path -Parent $MyInvocation.ScriptName
    $packagesFile = Join-Path $scriptDir "..\packages\windows"
    
    $results = @{
        build_packages = @{}
        test_packages = @{}
    }
    
    try {
        $packagesData = Get-Content $packagesFile -Raw | ConvertFrom-Json
        
        foreach ($package in $packagesData.build_packages) {
            $results.build_packages[$package] = Test-PackageInstalled -Package $package
        }
        
        foreach ($package in $packagesData.test_packages) {
            $results.test_packages[$package] = Test-PackageInstalled -Package $package
        }
    }
    catch {
        $results.error = "Unable to load packages file: $_"
    }
    
    return $results
}

function Get-MachineInfo {
    return @{
        timestamp = Get-Timestamp
        hostname = Get-HostnameInfo
        os = Get-OSInfo
        packages = Get-PackageInfo
    }
}

function Write-MachineInfo {
    param(
        [hashtable]$Data
    )
    
    try {
        $tempFile = [System.IO.Path]::GetTempFileName()
        
        $jsonData = $Data | ConvertTo-Json -Depth 10
        $jsonData | Out-File -FilePath $tempFile -Encoding UTF8
        
        try {
            if (Test-Path $OutputFile) {
                Remove-Item $OutputFile -Force
            }
            Move-Item $tempFile $OutputFile -Force
            Write-Host "Machine information successfully written to: $OutputFile"
            return $true
        }
        catch {
            Write-Host "Error: Unable to write to $OutputFile"
            Write-Host "Please ensure you have appropriate permissions (try running as Administrator)"
            Write-Host "Temporary output saved to: $tempFile"
            return $false
        }
    }
    catch {
        Write-Host "Error creating temporary file: $_"
        return $false
    }
}

function Main {
    Write-Host "Collecting Windows machine information..."
    
    $data = Get-MachineInfo
    
    if (Write-MachineInfo -Data $data) {
        Write-Host ""
        Write-Host "You can view the report with:"
        Write-Host "  type $OutputFile"
        Write-Host "  Get-Content $OutputFile | ConvertFrom-Json"
        exit 0
    }
    else {
        exit 1
    }
}

Main

