#!/usr/bin/env python3

# Some portions generated by IBM Bob

import os
import sys
import platform
import subprocess
import socket
import json
from datetime import datetime
import shutil
import tempfile


OUTPUT_FILE = "C:\\machine_info.json"


def get_timestamp():
    return datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")


def get_hostname():
    try:
        return socket.gethostname()
    except Exception:
        return "Unable to determine"


def get_os_info():
    os_name = "Windows"
    os_version = "Unknown"
    os_build = "Unknown"
    
    try:
        os_version = platform.version()
    except Exception:
        pass
    
    try:
        result = subprocess.run(['wmic', 'os', 'get', 'Caption', '/value'], 
                              capture_output=True, text=True, timeout=5)
        if result.returncode == 0:
            for line in result.stdout.split('\n'):
                if 'Caption=' in line:
                    os_name = line.split('=')[1].strip()
                    break
    except Exception:
        pass
    
    try:
        result = subprocess.run(['wmic', 'os', 'get', 'BuildNumber', '/value'], 
                              capture_output=True, text=True, timeout=5)
        if result.returncode == 0:
            for line in result.stdout.split('\n'):
                if 'BuildNumber=' in line:
                    os_build = line.split('=')[1].strip()
                    break
    except Exception:
        pass
    
    return {
        'name': os_name,
        'version': os_version,
        'build': os_build
    }


def check_packages():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    packages_file = os.path.join(script_dir, '../packages/windows')
    
    try:
        with open(packages_file, 'r') as f:
            packages_data = json.load(f)
    except Exception as e:
        return {
            'build_packages': {},
            'test_packages': {},
            'error': f'Unable to load packages file: {e}'
        }
    
    results = {
        'build_packages': {},
        'test_packages': {}
    }
    
    for package in packages_data.get('build_packages', []):
        path = shutil.which(package)
        results['build_packages'][package] = {
            'installed': path is not None,
            'path': path
        }
    
    for package in packages_data.get('test_packages', []):
        path = shutil.which(package)
        results['test_packages'][package] = {
            'installed': path is not None,
            'path': path
        }
    
    return results


def collect_info():
    return {
        'timestamp': get_timestamp(),
        'hostname': get_hostname(),
        'os': get_os_info(),
        'packages': check_packages()
    }


def write_output(data):
    try:
        with tempfile.NamedTemporaryFile(mode='w', delete=False, 
                                        prefix='machine_info_', suffix='.tmp',
                                        dir=os.path.dirname(OUTPUT_FILE)) as temp_file:
            temp_path = temp_file.name
            json.dump(data, temp_file, indent=2)
        
        try:
            if os.path.exists(OUTPUT_FILE):
                os.remove(OUTPUT_FILE)
            shutil.move(temp_path, OUTPUT_FILE)
            print(f"Machine information successfully written to: {OUTPUT_FILE}")
            return True
        except PermissionError:
            print(f"Error: Unable to write to {OUTPUT_FILE}")
            print("Please ensure you have appropriate permissions (try running as Administrator)")
            print(f"Temporary output saved to: {temp_path}")
            return False
        except Exception as e:
            print(f"Error: Unable to write to {OUTPUT_FILE}: {e}")
            print(f"Temporary output saved to: {temp_path}")
            return False
    
    except Exception as e:
        print(f"Error creating temporary file: {e}")
        return False


def main():
    print("Collecting Windows machine information...")
    
    data = collect_info()
    
    if write_output(data):
        print("")
        print("You can view the report with:")
        print(f"  type {OUTPUT_FILE}")
        print(f"  python -m json.tool {OUTPUT_FILE}")
        return 0
    else:
        return 1


if __name__ == "__main__":
    sys.exit(main())
