#!/usr/bin/env python3
# Check End-of-Life status for operating systems used by Adoptium machines.
# Some portions generated by IBM Bob

import sys
import os
import re
import json
import argparse
from datetime import datetime, timezone
from pathlib import Path
from dotenv import load_dotenv
import jenkins
import requests

def create_jenkins_server():

    # Load environment variables from .env file in the same directory
    script_dir = Path(__file__).parent
    env_path = script_dir / ".env"
    load_dotenv(env_path)
    
    # Get credentials from environment
    url = os.getenv('url')
    username = os.getenv('username')
    password = os.getenv('password')
    
    # Validate credentials
    if not all([url, username, password]):
        print("Error: Missing credentials in .env file")
        print("Required variables: url, username, password")
        sys.exit(1)
    
    # Create and return Jenkins server connection
    try:
        server = jenkins.Jenkins(url=url, username=username, password=password)
        # Test connection
        server.get_whoami()
        return server
    except Exception as e:
        print(f"Error: Could not connect to Jenkins server: {e}")
        sys.exit(1)

def get_all_nodes(server):

    try:
        all_nodes = server.get_nodes()
        
        # Filter nodes to keep only those with specific keywords
        keywords = ["test", "build", "dockerhost", "macos"]
        filtered_nodes = [
            node for node in all_nodes
            if any(keyword in node['name'].lower() for keyword in keywords)
        ]
        
        return filtered_nodes
    except Exception as e:
        print(f"Error: Could not retrieve nodes from Jenkins: {e}")
        sys.exit(1)

def get_node_labels(server, node_name):
    """Get labels for a specific node from Jenkins."""
    try:
        node_info = server.get_node_info(node_name)
        labels = node_info["assignedLabels"]
        return labels if labels else []
    except Exception as e:
        print(f"Warning: Could not retrieve labels for node {node_name}: {e}")
        return []

def extract_os_info(nodes, server):
    # Extract OS and version info from node name
    result = []
    
    for node in nodes:
        node_name = node['name']
        os_name = None
        version = None

        # List of ignores:
        if 'win' in node_name.lower():
            continue

        if 'macos' in node_name.lower():
            continue

        if 'gha' in node_name.lower():
            continue

        if 'vagrant' in node_name.lower():
            continue

        if 'Built-In' in node_name.lower() or 'eclipse' in node_name.lower() or 'jenkins' in node_name.lower() or 'trss' in node_name.lower():
            continue
        
        # Switch based on substrings found in node name
        if 'ubuntu' in node_name.lower():
            os_name = 'ubuntu'
            # Look for 4-digit number after 'ubuntu' (e.g., ubuntu1604, ubuntu2004)
            match = re.search(r'ubuntu(\d{4})', node_name, re.IGNORECASE)
            if match:
                version_str = match.group(1)
                # Split into XX.YY format (e.g., 1604 -> 16.04, 2004 -> 20.04)
                version = f"{version_str[:2]}.{version_str[2:]}"

        elif 'rhel' in node_name.lower() or 'ubi' in node_name.lower():
            os_name = 'rhel'
            # Look for first digit after 'rhel' or 'ubi' (e.g., rhel78 -> 7, ubi9 -> 9)
            match = re.search(r'(?:rhel|ubi)(\d)', node_name, re.IGNORECASE)
            if match:
                version = match.group(1)
                
        elif 'centos' in node_name.lower():
            # Check for centos-stream first (more specific)
            if 'centosstream' in node_name.lower():
                os_name = 'centos-stream'
                # Look for number after 'centosstream' (e.g., centosstream10 -> 10)
                match = re.search(r'centosstream(\d+)', node_name, re.IGNORECASE)
                if match:
                    version = match.group(1)
            else:
                # Regular centos
                os_name = 'centos'
                # Look for first digit after 'centos' (e.g., centos7 -> 7)
                match = re.search(r'centos(\d)', node_name, re.IGNORECASE)
                if match:
                    version = match.group(1)

        elif 'fedora' in node_name.lower():
            os_name = 'fedora'
            # Look for 2-digit number after 'fedora' (e.g., fedora38 -> 38, fedora44 -> 44)
            match = re.search(r'fedora(\d{2})', node_name, re.IGNORECASE)
            if match:
                version = match.group(1)

        elif 'alpine' in node_name.lower():
            os_name = 'alpine'
            # Look for 3-digit number after 'alpine' (e.g., alpine321 -> 3.21, alpine324 -> 3.24)
            match = re.search(r'alpine(\d{3})', node_name, re.IGNORECASE)
            if match:
                version_str = match.group(1)
                # Format as X.YZ (e.g., 321 -> 3.21)
                version = f"{version_str[0]}.{version_str[1:]}"

        elif 'sles' in node_name.lower():
            os_name = 'sles'
            # Extract major version from node name (e.g., sles12 -> 12)
            match = re.search(r'sles(\d+)', node_name, re.IGNORECASE)
            if match:
                major = match.group(1)
                # Get labels and search for major.minor pattern (e.g., 12.5)
                labels = get_node_labels(server, node_name)
                for label in labels:
                    label_name = label.get('name', '')
                    # Look for pattern like "12.5" where 12 matches the major version
                    version_match = re.match(rf'^{major}\.(\d+)$', label_name)
                    if version_match:
                        version = label_name  # e.g., "12.5"
                        break

        elif 'aix' in node_name.lower():
            os_name = 'aix'
            # Extract major version from node name (e.g., aix72 -> 7.2, aix73 -> 7.3)
            match = re.search(r'aix(\d)(\d)', node_name, re.IGNORECASE)
            if match:
                major = match.group(1)
                minor = match.group(2)
                # Default version is major.minor.0
                version = f"{major}.{minor}.0"
                
                # Get labels and search for TL-X pattern to get patch version
                labels = get_node_labels(server, node_name)
                for label in labels:
                    label_name = label.get('name', '')
                    # Look for TL-X pattern (e.g., TL-5)
                    tl_match = re.match(r'^TL-(\d+)$', label_name)
                    if tl_match:
                        patch = tl_match.group(1)
                        version = f"{major}.{minor}.{patch}"
                        break

        result.append({
            "name": node_name,
            "os": os_name,
            "version": version
        })
    
    return result

# Operating systems that publish LTS releases — only these use the LTS lookup.
OS_WITH_LTS = {'ubuntu'}

def get_latest_version(os_name, base_url, cache):
    """Return the latest relevant version for an OS, cached per OS.

    For OS types that publish LTS releases (e.g. Ubuntu), return the name of
    the most recent LTS release.  For all other OS types, return the name of
    the overall latest release via the /releases/latest endpoint.
    """
    if os_name in cache:
        return cache[os_name]

    latest = None
    try:
        if os_name in OS_WITH_LTS:
            # Fetch the full product listing and find the first LTS release
            response = requests.get(f"{base_url}/{os_name}", timeout=10)
            if response.status_code == 200:
                data = response.json()
                releases = data.get('result', {}).get('releases', [])
                for release in releases:
                    if release.get('isLts') is True:
                        latest = release.get('name')
                        break
        else:
            # centos EOL tracking is done under the centos-stream product
            lookup_name = 'centos-stream' if os_name == 'centos' else os_name
            # Fetch only the latest release
            response = requests.get(f"{base_url}/{lookup_name}/releases/latest", timeout=10)
            if response.status_code == 200:
                data = response.json()
                latest = data.get('result', {}).get('name')
    except requests.exceptions.RequestException as e:
        print(f"Warning: Could not retrieve product info for {os_name}: {e}")

    cache[os_name] = latest
    return latest


def check_eol_status(os_info_list):

    result = []
    base_url = "https://endoflife.date/api/v1/products"
    lts_cache = {}

    for item in os_info_list:
        node_name = item['name']
        os_name = item['os']
        version = item['version']

        # UBI EOL follows the same schedule as RHEL
        if os_name == 'ubi':
            os_name = 'rhel'
        
        # Initialize EOL fields
        is_eol = None
        eol_from = None
        latest_lts = None
        
        # Skip if OS or version is unknown
        if os_name == 'unknown' or version == 'unknown':
            result.append({
                "name": node_name,
                "os": os_name,
                "version": version,
                "isEOL": is_eol,
                "eolFrom": eol_from,
                "latestLts": latest_lts
            })
            continue
        
        # Query the endoflife.date API for version-specific EOL data
        try:
            # API endpoint: /api/v1/products/{os}/releases/{version}
            url = f"{base_url}/{os_name}/releases/{version}"
            response = requests.get(url, timeout=10)
            
            if response.status_code == 200:
                data = response.json()
                
                # Extract from 'result' object
                if 'result' in data:
                    result_data = data['result']
                    is_eol = result_data.get('isEol', None)
                    eol_from = result_data.get('eolFrom', None)
                else:
                    # Fallback if structure is different
                    is_eol = None
                    eol_from = None
            else:
                # API returned non-200 status (product/version not found)
                is_eol = None
                eol_from = None
                
        except requests.exceptions.RequestException as e:
            # Network error or timeout
            print(f"Warning: Could not check EOL status for {node_name} ({os_name} {version}): {e}")
            is_eol = None
            eol_from = None

        # Fetch latest LTS for this OS (cached)
        latest_lts = get_latest_version(os_name, base_url, lts_cache)
        # Add to result
        result.append({
            "name": node_name,
            "os": os_name,
            "version": version,
            "isEOL": is_eol,
            "eolFrom": eol_from,
            "latestLts": latest_lts
        })
    
    return result

def main():
    """Main function."""
    parser = argparse.ArgumentParser(description="Check EOL status for Jenkins node operating systems.")
    parser.add_argument('-q', '--quiet', action='store_true',
                        help="Suppress informational output; print only the JSON result.")
    args = parser.parse_args()

    def log(msg):
        if not args.quiet:
            print(msg)

    log("Connecting to Jenkins server...")
    server = create_jenkins_server()
    log("Connected successfully!")

    log("\nRetrieving all nodes...")
    nodes = get_all_nodes(server)
    log(f"Found {len(nodes)} nodes")

    log("\nExtracting OS information...")
    os_info = extract_os_info(nodes, server)

    log("\nChecking EOL status from endoflife.date API...")
    eol_info = check_eol_status(os_info)

    log("\nNode EOL Information (JSON):")
    output = {
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "EOL_data": eol_info
    }
    print(json.dumps(output, indent=2))

    return 0

if __name__ == "__main__":
    sys.exit(main())
