#!/usr/bin/env python3
# Check End-of-Life status for operating systems used by Adoptium machines.
# Some portions generated by IBM Bob

import sys
import os
import re
import json
from pathlib import Path
from dotenv import load_dotenv
import jenkins
import requests
from datetime import datetime


def create_jenkins_server():

    # Load environment variables from .env file in the same directory
    script_dir = Path(__file__).parent
    env_path = script_dir / ".env"
    load_dotenv(env_path)
    
    # Get credentials from environment
    url = os.getenv('url')
    username = os.getenv('username')
    password = os.getenv('password')
    
    # Validate credentials
    if not all([url, username, password]):
        print("Error: Missing credentials in .env file")
        print("Required variables: url, username, password")
        sys.exit(1)
    
    # Create and return Jenkins server connection
    try:
        server = jenkins.Jenkins(url=url, username=username, password=password)
        # Test connection
        server.get_whoami()
        return server
    except Exception as e:
        print(f"Error: Could not connect to Jenkins server: {e}")
        sys.exit(1)


def get_all_nodes(server):

    try:
        all_nodes = server.get_nodes()
        
        # Filter nodes to keep only those with specific keywords
        keywords = ["test", "build", "dockerhost", "macos"]
        filtered_nodes = [
            node for node in all_nodes
            if any(keyword in node['name'].lower() for keyword in keywords)
        ]
        
        return filtered_nodes
    except Exception as e:
        print(f"Error: Could not retrieve nodes from Jenkins: {e}")
        sys.exit(1)


def extract_os_info(nodes):
    # Extract OS and version info from node name
    result = []
    
    for node in nodes:
        node_name = node['name']
        os_name = None
        version = None

        # Ignore dynamic windows nodes
        if 'test-win' in node_name.lower():
            continue


        if 'macos' in node_name.lower():
            # GHA dyanmic mac nodes
            match = re.search(r'-macos(\d+)', node_name, re.IGNORECASE)
            if match:
                os_name = 'macos'
                version = match.group(1)
        else:
            parts = node_name.split('-')
            if len(parts) >= 3:
                segment = parts[2]  # Third part (index 2)

                # Ubuntu pattern: ubuntu2404 -> ubuntu 24.04
                match = re.match(r'(ubuntu)(\d{2})(\d{2})', segment, re.IGNORECASE)
                if match:
                    os_name = match.group(1).lower()
                    version = f"{match.group(2)}.{match.group(3)}"
                else:
                    # AIX pattern: aix72 -> aix 7.2.0
                    match = re.match(r'(aix)(\d)(\d)', segment, re.IGNORECASE)
                    if match:
                        os_name = match.group(1).lower()
                        version = f"{match.group(2)}.{match.group(3)}.0"
                    else:
                        # CentOS Stream pattern: centosstream10 -> centos-stream 10
                        match = re.match(r'centosstream(\d+)', segment, re.IGNORECASE)
                        if match:
                            os_name = 'centos-stream'
                            version = match.group(1)
                        else:
                            # CentOS pattern: centos74 -> centos 7
                            match = re.match(r'(centos)(\d{2})', segment, re.IGNORECASE)
                            if match:
                                os_name = match.group(1).lower()
                                version = match.group(2)[0]  # Take first digit only
                            else:
                                # SLES pattern: sles15 -> sles 15.0
                                match = re.match(r'(sles)(\d+)', segment, re.IGNORECASE)
                                if match:
                                    os_name = match.group(1).lower()
                                    version = f"{match.group(2)}.0"
                                else:
                                    # Alpine pattern: alpine321 -> alpine 3.21
                                    match = re.match(r'(alpine)(\d)(\d{2})', segment, re.IGNORECASE)
                                    if match:
                                        os_name = match.group(1).lower()
                                        version = f"{match.group(2)}.{match.group(3)}"
                                    else:
                                        # Generic pattern
                                        match = re.match(r'([a-z]+?)(\d+(?:\.\d+)*)', segment, re.IGNORECASE)
                                        if match:
                                            os_name = match.group(1).lower()
                                            version = match.group(2)
        
        result.append({
            "name": node_name,
            "os": os_name,
            "version": version
        })
    
    return result


def check_eol_status(os_info_list):

    result = []
    base_url = "https://endoflife.date/api/v1/products"
    
    for item in os_info_list:
        node_name = item['name']
        os_name = item['os']
        version = item['version']

        # UBI EOL follows the same schedule as RHEL
        if os_name == 'ubi':
            os_name = 'rhel'
        
        # Initialize EOL fields
        is_eol = None
        eol_from = None
        
        # Skip if OS or version is unknown
        if os_name == 'unknown' or version == 'unknown':
            result.append({
                "name": node_name,
                "os": os_name,
                "version": version,
                "isEOL": is_eol,
                "eolFrom": eol_from
            })
            continue
        
        # Query the endoflife.date API
        try:
            # API endpoint: /api/v1/products/{os}/releases/{version}
            url = f"{base_url}/{os_name}/releases/{version}"
            response = requests.get(url, timeout=10)
            
            if response.status_code == 200:
                data = response.json()
                
                # Extract from 'result' object
                if 'result' in data:
                    result_data = data['result']
                    is_eol = result_data.get('isEol', None)
                    eol_from = result_data.get('eolFrom', None)
                else:
                    # Fallback if structure is different
                    is_eol = None
                    eol_from = None
            else:
                # API returned non-200 status (product/version not found)
                is_eol = None
                eol_from = None
                
        except requests.exceptions.RequestException as e:
            # Network error or timeout
            print(f"Warning: Could not check EOL status for {node_name} ({os_name} {version}): {e}")
            is_eol = None
            eol_from = None
        
        # Add to result
        result.append({
            "name": node_name,
            "os": os_name,
            "version": version,
            "isEOL": is_eol,
            "eolFrom": eol_from
        })
    
    return result


def main():
    """Main function."""
    print("Connecting to Jenkins server...")
    server = create_jenkins_server()
    print("Connected successfully!")
    
    print("\nRetrieving all nodes...")
    nodes = get_all_nodes(server)
    print(f"Found {len(nodes)} nodes")
    
    # Extract OS information
    print("\nExtracting OS information...")
    os_info = extract_os_info(nodes)
    
    # Check EOL status for each node
    print("\nChecking EOL status from endoflife.date API...")
    eol_info = check_eol_status(os_info)
    
    # Display as JSON
    print("\nNode EOL Information (JSON):")
    print(json.dumps(eol_info, indent=2))
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
