#! /usr/bin/env bash

# Nagios Plugins to check the timesync of a system (on systems based on systemd)

# Name of relevant lines change over time. Add new line if necessary.
SERVICE_STATE_KEYS=(
    "Network time on" # Ubuntu 16.04
    "systemd-timesyncd.service" # Ubuntu 18.04
    "NTP service" # Ubuntu 20.04
)
SYNC_STATE_KEYS=(
    "System clock synchronized" # Ubuntu 18.04 and newer
    "NTP synchronized" # Ubuntu 16.04
)
is_ok() {
    [[ "$1" =~ ^(active|yes)$ ]] 
}
# Joins the entries with a pipe character, so that they look like "entry1|entry2"
SERVICE_STATUS_LINES=$(IFS=\| ; echo "${SERVICE_STATE_KEYS[*]}")
SYNC_STATUS_LINES=$(IFS=\| ; echo "${SYNC_STATE_KEYS[*]}")
STATE=$( timedatectl )
SERVICE_STATE=$( echo "$STATE" | awk -F ':' "BEGIN{IGNORECASE=1} /$SERVICE_STATUS_LINES/{gsub(/ /, \"\", \$2); print \$2}")
SYNC_STATE=$( echo "$STATE" | awk -F ':' "BEGIN{IGNORECASE=1} /$SYNC_STATUS_LINES/{gsub(/ /, \"\", \$2); print \$2}")
if ! is_ok "$SERVICE_STATE" && ! is_ok "$SYNC_STATE" ; then
    echo "CRITICAL - There's something terribly wrong"
    exit 2
fi
if ! is_ok "$SERVICE_STATE" ; then
    echo "WARNING - Service systemd-timesyncd not running"
    exit 1
fi
if ! is_ok "$SYNC_STATE" ; then
    echo "WARNING - Time not synchronized"
    exit 1
fi
if is_ok "$SERVICE_STATE" && is_ok "$SYNC_STATE" ; then
    echo "OK - Time synchronized"
    exit 0
fi
echo "UNKNOWN – Please check time synchronization"
echo 3
