---
##########
# cygwin #
##########
- name: Test if Cygwin is already installed (jq.exe as marker)
  win_stat:
    path: "{{ Cygwin_INST_DIR }}\\bin\\jq.exe"
  register: cygwin_installed
  tags: cygwin

- name: Ensure temp and package directories exist
  win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - "C:\\temp"
    - "{{ Cygwin_PACKAGE_DIR }}"
    - "{{ Cygwin_CACHE_DIR }}"
  tags: cygwin

- name: Retrieve Cygwin setup
  win_get_url:
    url: "https://cygwin.com/setup-x86_64.exe"
    dest: "C:\\temp\\cygwin.exe"
    force: no
    checksum: "2c9f2fb56e1fb687b5d9680afa8f8b06e6214f0e483096af0eae1946431226c5" # v3.6.7-1
    checksum_algorithm: sha256
  when: not cygwin_installed.stat.exists
  register: cygwin_download
  tags: cygwin

# Note: Gawk is pinned due to this upstream bug : https://bugs.openjdk.org/browse/JDK-8314555 GAWK for cygwin must be <= 5.3.2-1
- name: Install Cygwin
  win_shell: |
      Start-Process -Wait -FilePath 'C:\temp\cygwin.exe' -ArgumentList '--packages autoconf,automake,bsdtar,cmake,cpio,curl,gawk=5.3.2-1,gcc-core,git,gnupg,gnupg2,grep,jq,libtool,make,mingw64-x86_64-gcc-core,perl,rsync,unzip,wget,zip --quiet-mode --download --local-install --delete-orphans --site https://mirrors.kernel.org/sourceware/cygwin/ --local-package-dir C:\cygwin_packages --root C:\cygwin64'
  args:
    executable: powershell
  when: not cygwin_installed.stat.exists
  tags: cygwin

- name: Change git config to not replace Line endings
  win_shell: "C:/cygwin64/bin/git config --system core.autocrlf false"
  tags: cygwin

- name: Remove c:\cygwin64\bin from the path if it exists
  win_path:
    name: PATH
    elements:
      - 'C:\cygwin64\bin'
    scope: machine
    state: absent
  when: (not cygwin_installed.stat.exists)
  tags: cygwin

- name: Add C:\cygwin64\bin to the front of the path
  win_shell: |
    [Environment]::SetEnvironmentVariable("Path", "C:\cygwin64\bin;" + $env:Path, [System.EnvironmentVariableTarget]::Machine)
  args:
    executable: powershell
  when: (not cygwin_installed.stat.exists)
  tags: cygwin

- name: Reboot machine for PATH changes to take effect
  win_reboot:
    reboot_timeout: 1800
  when: (not cygwin_installed.stat.exists)
  tags:
    - cygwin
    - reboot
